# Generated by Django 3.2.9 on 2021-11-22 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20211122_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='authur',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='genere',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='page',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
